### ISSUE TITLE
Leverage hostsfile cookbook?

### ISSUE THREAD

**Issue by sethvargo** [SimpleFinance/chef-proxy#3]
Hey Simple!

I wanted to point out the [hostsfile cookbook](https://github.com/customink-webops/hostsfile) and recommend it for actually managing the hostsfile. It supports all the defined actions plus priority, etc. And it's fully tested by ChefSpec and test-kitchen. 

I currently manage the project, but I would recommend it even if I didn't :smile:

**Comment by jdinthe** [comment]
Hey Seth,

This cookbook is going through some slight churn as we integrate it in a spot or two. Once we're through that, we'll definitely take a look at `hostsfile` -- thanks.

**Comment by sethvargo** [comment]
@jakedavis thanks!
